# Generated by Django 2.2.7 on 2020-07-23 10:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('plate_count', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('payment_method', models.PositiveIntegerField(choices=[(1, 'Cash'), (2, 'PayTM/GPay'), (3, 'Credit')])),
                ('meal_type', models.PositiveIntegerField(choices=[(1, 'Lunch'), (2, 'Dinner')])),
                ('confirmation_status', models.BooleanField(default=False)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
